/** Photo filenames committed under /public/assets (from GitHub media). */
export const galleryImagePaths = [
  "/assets/photo_001.jpg",
  "/assets/photo_002.webp",
  "/assets/photo_003.jpg",
  "/assets/photo_004.jpg",
  "/assets/photo_005.jpg",
  "/assets/photo_006.jpg",
  "/assets/photo_007.jpg",
  "/assets/photo_008.jpg",
  "/assets/photo_009.jpg",
  "/assets/photo_010.jpg",
  "/assets/photo_011.jpg",
  "/assets/photo_012.jpg",
  "/assets/photo_013.jpg",
  "/assets/photo_014.jpg",
  "/assets/photo_015.jpg",
  "/assets/photo_016.jpg",
  "/assets/photo_017.jpg",
  "/assets/photo_018.jpg",
  "/assets/photo_019.jpg",
  "/assets/photo_020.jpg",
  "/assets/photo_021.jpg",
  "/assets/photo_022.jpg",
  "/assets/photo_023.jpg",
  "/assets/photo_024.jpg",
  "/assets/photo_025.jpg",
  "/assets/photo_026.jpg",
  "/assets/photo_027.jpg",
  "/assets/photo_028.jpg",
  "/assets/photo_029.jpg",
  "/assets/photo_030.jpg",
  "/assets/photo_031.jpg",
  "/assets/photo_032.jpg",
  "/assets/photo_033.jpg",
] as const;
